use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DcdcState {
    // DCDC1C control
    pub dcdc_operational_command: u8,
    pub dcdc_low_side_voltage_setpoint: f64,
    pub dcdc_high_side_voltage_setpoint: f64,
    pub dcdc_control_counter: u64,

    // DCDC1OS operating status
    pub dcdc1os_hvil_status: u8,
    pub dcdc1os_loadshed_request: u8,
    pub dcdc1os_operational_status: u8,
    pub dcdc1os_operating_status_counter: u8,
    pub dcdc1os_operating_status_crc: u8,
    pub dcdc1os_power_limit_high_side_current: u8,
    pub dcdc1os_power_limit_low_side_current: u8,
    pub dcdc1os_power_limit_high_side_voltage_min: u8,
    pub dcdc1os_power_limit_high_side_voltage_max: u8,
    pub dcdc1os_power_limit_low_side_voltage_min: u8,
    pub dcdc1os_power_limit_low_side_voltage_max: u8,
    pub dcdc1os_power_limit_converter_temperature: u8,
    pub dcdc1os_power_limit_electronic_filter_temperature: u8,
    pub dcdc1os_power_limit_power_electronics_temperature: u8,
    pub dcdc1os_power_limit_sli_battery_terminal_voltage: u8,
    pub dcdc1os_power_limit_sli_battery_terminal_current: u8,
    pub dcdc1os_power_limit_sli_battery_terminal_temperature: u8,
    pub dcdc1os_power_limit_undefined_reason: u8,

    // DCDC1SBS battery status
    pub dcdc1sbs_terminal_current: f64,
    pub dcdc1sbs_terminal_voltage: f64,
    pub dcdc1sbs_terminal_temperature: f64,

    // DCDC1S2 status 2
    pub dcdc1s2_high_side_power: f64,
    pub dcdc1s2_low_side_power: f64,
    pub dcdc1s2_high_side_ground_voltage: f64,

    // DCDC2SBS battery status
    pub dcdc2sbs_terminal_voltage: f64,
    pub dcdc2sbs_terminal_current: f64,
    pub dcdc2sbs_terminal_temperature: f64,

    // DCDC2S2 status 2
    pub dcdc2s2_high_side_power: f64,
    pub dcdc2s2_low_side_power: f64,
    pub dcdc2s2_high_side_ground_voltage: f64,

    // === Batch 9: Extended Power Conversion Messages ===

    // DCDC1HL DC/DC Converter 1 High Side Limits
    pub dcdc1hl_high_side_voltage_min_limit: f64,
    pub dcdc1hl_high_side_voltage_max_limit: f64,
    pub dcdc1hl_high_side_current_max_limit: f64,
    pub dcdc1hl_high_side_current_min_limit: f64,

    // DCDC1LL DC/DC Converter 1 Low Side Limits
    pub dcdc1ll_low_side_voltage_min_limit: f64,
    pub dcdc1ll_low_side_voltage_max_limit: f64,
    pub dcdc1ll_low_side_current_max_limit: f64,
    pub dcdc1ll_low_side_current_min_limit: f64,

    // DCDC1T DC/DC Converter 1 Temperature
    pub dcdc1t_converter_temperature: f64,
    pub dcdc1t_electronic_filter_temperature: f64,
    pub dcdc1t_power_electronics_temperature: f64,
    pub dcdc1t_coolant_in_temperature: f64,
    pub dcdc1t_coolant_out_temperature: f64,

    // DCDC1V DC/DC Converter 1 Voltage
    pub dcdc1v_ignition_voltage: f64,
    pub dcdc1v_unswitched_sli_voltage: f64,

    // DCDC1VC DC/DC Converter 1 Voltage/Current
    pub dcdc1vc_low_side_voltage: f64,
    pub dcdc1vc_low_side_current: f64,
    pub dcdc1vc_high_side_voltage: f64,
    pub dcdc1vc_high_side_current: f64,

    // DCDC1LD DC/DC Converter 1 Lifetime Data
    pub dcdc1ld_total_high_side_energy: f64,
    pub dcdc1ld_total_low_side_energy: f64,
    pub dcdc1ld_total_high_side_charge: f64,
    pub dcdc1ld_total_low_side_charge: f64,

    // DCDC1SBL DC/DC Converter 1 SLI Battery Limits
    pub dcdc1sbl_voltage_max_limit: f64,
    pub dcdc1sbl_current_max_limit: f64,
    pub dcdc1sbl_temperature_max_limit: f64,

    // DCDC1CFG1 DC/DC Converter 1 Configuration 1
    pub dcdc1cfg1_hs_voltage_min_limit: f64,
    pub dcdc1cfg1_hs_voltage_max_limit: f64,
    pub dcdc1cfg1_hs_current_max_limit: f64,
    pub dcdc1cfg1_ls_voltage_min_limit: f64,
    pub dcdc1cfg1_ls_voltage_max_limit: f64,
    pub dcdc1cfg1_ls_current_max_limit: f64,
    pub dcdc1cfg1_sli_voltage_max_limit: f64,
    pub dcdc1cfg1_sli_current_max_limit: f64,
    pub dcdc1cfg1_sli_temperature_max_limit: f64,
    pub dcdc1cfg1_ls_voltage_buck_default: f64,
    pub dcdc1cfg1_ls_current_min_limit: f64,
    pub dcdc1cfg1_hs_current_min_limit: f64,

    // DCDC2C DC/DC Converter 2 Control
    pub dcdc2c_operational_command: u8,
    pub dcdc2c_control_counter: u8,
    pub dcdc2c_low_side_voltage_buck_setpoint: f64,
    pub dcdc2c_high_side_voltage_boost_setpoint: f64,
    pub dcdc2c_low_side_voltage_buck_default_setpoint: f64,
    pub dcdc2c_control_crc: u8,

    // DCDC2OS DC/DC Converter 2 Operating Status
    pub dcdc2os_operational_status: u8,
    pub dcdc2os_hvil_status: u8,
    pub dcdc2os_loadshed_request: u8,
    pub dcdc2os_power_limit_high_side_current: u8,
    pub dcdc2os_power_limit_low_side_current: u8,
    pub dcdc2os_power_limit_high_side_voltage_min: u8,
    pub dcdc2os_power_limit_high_side_voltage_max: u8,
    pub dcdc2os_power_limit_low_side_voltage_min: u8,
    pub dcdc2os_power_limit_low_side_voltage_max: u8,
    pub dcdc2os_power_limit_converter_temperature: u8,
    pub dcdc2os_power_limit_electronic_filter_temperature: u8,
    pub dcdc2os_power_limit_power_electronics_temperature: u8,
    pub dcdc2os_power_limit_sli_battery_terminal_voltage: u8,
    pub dcdc2os_power_limit_sli_battery_terminal_current: u8,
    pub dcdc2os_power_limit_sli_battery_terminal_temperature: u8,
    pub dcdc2os_power_limit_undefined_reason: u8,
    pub dcdc2os_operating_status_counter: u8,
    pub dcdc2os_operating_status_crc: u8,

    // DCDC2HL DC/DC Converter 2 High Side Limits
    pub dcdc2hl_high_side_voltage_min_limit: f64,
    pub dcdc2hl_high_side_voltage_max_limit: f64,
    pub dcdc2hl_high_side_current_max_limit: f64,
    pub dcdc2hl_high_side_current_min_limit: f64,

    // DCDC2LL DC/DC Converter 2 Low Side Limits
    pub dcdc2ll_low_side_voltage_min_limit: f64,
    pub dcdc2ll_low_side_voltage_max_limit: f64,
    pub dcdc2ll_low_side_current_max_limit: f64,
    pub dcdc2ll_low_side_current_min_limit: f64,

    // DCDC2T DC/DC Converter 2 Temperature
    pub dcdc2t_converter_temperature: f64,
    pub dcdc2t_electronic_filter_temperature: f64,
    pub dcdc2t_power_electronics_temperature: f64,
    pub dcdc2t_coolant_in_temperature: f64,
    pub dcdc2t_coolant_out_temperature: f64,

    // DCDC2V DC/DC Converter 2 Voltage
    pub dcdc2v_ignition_voltage: f64,
    pub dcdc2v_unswitched_sli_voltage: f64,

    // DCDC2VC DC/DC Converter 2 Voltage/Current
    pub dcdc2vc_low_side_voltage: f64,
    pub dcdc2vc_low_side_current: f64,
    pub dcdc2vc_high_side_voltage: f64,
    pub dcdc2vc_high_side_current: f64,

    // DCDC2LD DC/DC Converter 2 Lifetime Data
    pub dcdc2ld_total_high_side_energy: f64,
    pub dcdc2ld_total_low_side_energy: f64,
    pub dcdc2ld_total_high_side_charge: f64,
    pub dcdc2ld_total_low_side_charge: f64,

    // DCDC2SBL DC/DC Converter 2 SLI Battery Limits
    pub dcdc2sbl_voltage_max_limit: f64,
    pub dcdc2sbl_current_max_limit: f64,
    pub dcdc2sbl_temperature_max_limit: f64,

    // DCDC2CFG1 DC/DC Converter 2 Configuration 1
    pub dcdc2cfg1_hs_voltage_min_limit: f64,
    pub dcdc2cfg1_hs_voltage_max_limit: f64,
    pub dcdc2cfg1_hs_current_max_limit: f64,
    pub dcdc2cfg1_ls_voltage_min_limit: f64,
    pub dcdc2cfg1_ls_voltage_max_limit: f64,
    pub dcdc2cfg1_ls_current_max_limit: f64,
    pub dcdc2cfg1_sli_voltage_max_limit: f64,
    pub dcdc2cfg1_sli_current_max_limit: f64,
    pub dcdc2cfg1_sli_temperature_max_limit: f64,
    pub dcdc2cfg1_ls_voltage_buck_default: f64,
    pub dcdc2cfg1_ls_current_min_limit: f64,
    pub dcdc2cfg1_hs_current_min_limit: f64,

    // DCDC3C DC/DC Converter 3 Control
    pub dcdc3c_operational_command: u8,
    pub dcdc3c_control_counter: u8,
    pub dcdc3c_low_side_voltage_buck_setpoint: f64,
    pub dcdc3c_high_side_voltage_boost_setpoint: f64,
    pub dcdc3c_low_side_voltage_buck_default_setpoint: f64,
    pub dcdc3c_control_crc: u8,

    // DCDC3OS DC/DC Converter 3 Operating Status
    pub dcdc3os_operational_status: u8,
    pub dcdc3os_hvil_status: u8,
    pub dcdc3os_loadshed_request: u8,
    pub dcdc3os_power_limit_high_side_current: u8,
    pub dcdc3os_power_limit_low_side_current: u8,
    pub dcdc3os_power_limit_high_side_voltage_min: u8,
    pub dcdc3os_power_limit_high_side_voltage_max: u8,
    pub dcdc3os_power_limit_low_side_voltage_min: u8,
    pub dcdc3os_power_limit_low_side_voltage_max: u8,
    pub dcdc3os_power_limit_converter_temperature: u8,
    pub dcdc3os_power_limit_electronic_filter_temperature: u8,
    pub dcdc3os_power_limit_power_electronics_temperature: u8,
    pub dcdc3os_power_limit_sli_battery_terminal_voltage: u8,
    pub dcdc3os_power_limit_sli_battery_terminal_current: u8,
    pub dcdc3os_power_limit_sli_battery_terminal_temperature: u8,
    pub dcdc3os_power_limit_undefined_reason: u8,
    pub dcdc3os_operating_status_counter: u8,
    pub dcdc3os_operating_status_crc: u8,

    // DCDC3S2 DC/DC Converter 3 Status 2
    pub dcdc3s2_low_side_power: f64,
    pub dcdc3s2_high_side_power: f64,
    pub dcdc3s2_high_side_ground_voltage: f64,

    // DCDC3SBS DC/DC Converter 3 SLI Battery Status
    pub dcdc3sbs_terminal_voltage: f64,
    pub dcdc3sbs_terminal_current: f64,
    pub dcdc3sbs_terminal_temperature: f64,

    // DCDC3T DC/DC Converter 3 Temperature
    pub dcdc3t_converter_temperature: f64,
    pub dcdc3t_electronic_filter_temperature: f64,
    pub dcdc3t_power_electronics_temperature: f64,
    pub dcdc3t_coolant_in_temperature: f64,
    pub dcdc3t_coolant_out_temperature: f64,

    // DCDC3V DC/DC Converter 3 Voltage
    pub dcdc3v_ignition_voltage: f64,
    pub dcdc3v_unswitched_sli_voltage: f64,

    // DCDC3VC DC/DC Converter 3 Voltage/Current
    pub dcdc3vc_low_side_voltage: f64,
    pub dcdc3vc_low_side_current: f64,
    pub dcdc3vc_high_side_voltage: f64,
    pub dcdc3vc_high_side_current: f64,

    // DCDC3SBL DC/DC Converter 3 SLI Battery Limits
    pub dcdc3sbl_voltage_max_limit: f64,
    pub dcdc3sbl_current_max_limit: f64,
    pub dcdc3sbl_temperature_max_limit: f64,

    // DCDC3LL DC/DC Converter 3 Low Side Limits
    pub dcdc3ll_low_side_voltage_min_limit: f64,
    pub dcdc3ll_low_side_voltage_max_limit: f64,
    pub dcdc3ll_low_side_current_max_limit: f64,
    pub dcdc3ll_low_side_current_min_limit: f64,

    // DCDC3HL DC/DC Converter 3 High Side Limits
    pub dcdc3hl_high_side_voltage_min_limit: f64,
    pub dcdc3hl_high_side_voltage_max_limit: f64,
    pub dcdc3hl_high_side_current_max_limit: f64,
    pub dcdc3hl_high_side_current_min_limit: f64,

    // DCDC3LD DC/DC Converter 3 Lifetime Data
    pub dcdc3ld_total_high_side_energy: f64,
    pub dcdc3ld_total_low_side_energy: f64,
    pub dcdc3ld_total_high_side_charge: f64,
    pub dcdc3ld_total_low_side_charge: f64,

    // DCDC3CFG1 DC/DC Converter 3 Configuration 1
    pub dcdc3cfg1_hs_voltage_min_limit: f64,
    pub dcdc3cfg1_hs_voltage_max_limit: f64,
    pub dcdc3cfg1_hs_current_max_limit: f64,
    pub dcdc3cfg1_ls_voltage_min_limit: f64,
    pub dcdc3cfg1_ls_voltage_max_limit: f64,
    pub dcdc3cfg1_ls_current_max_limit: f64,
    pub dcdc3cfg1_sli_voltage_max_limit: f64,
    pub dcdc3cfg1_sli_current_max_limit: f64,
    pub dcdc3cfg1_sli_temperature_max_limit: f64,
    pub dcdc3cfg1_ls_voltage_buck_default: f64,
    pub dcdc3cfg1_ls_current_min_limit: f64,
    pub dcdc3cfg1_hs_current_min_limit: f64,

    // DCDC4C DC/DC Converter 4 Control
    pub dcdc4c_operational_command: u8,
    pub dcdc4c_control_counter: u8,
    pub dcdc4c_low_side_voltage_buck_setpoint: f64,
    pub dcdc4c_high_side_voltage_boost_setpoint: f64,
    pub dcdc4c_low_side_voltage_buck_default_setpoint: f64,
    pub dcdc4c_control_crc: u8,

    // DCDC4OS DC/DC Converter 4 Operating Status
    pub dcdc4os_operational_status: u8,
    pub dcdc4os_hvil_status: u8,
    pub dcdc4os_loadshed_request: u8,
    pub dcdc4os_power_limit_high_side_current: u8,
    pub dcdc4os_power_limit_low_side_current: u8,
    pub dcdc4os_power_limit_high_side_voltage_min: u8,
    pub dcdc4os_power_limit_high_side_voltage_max: u8,
    pub dcdc4os_power_limit_low_side_voltage_min: u8,
    pub dcdc4os_power_limit_low_side_voltage_max: u8,
    pub dcdc4os_power_limit_converter_temperature: u8,
    pub dcdc4os_power_limit_electronic_filter_temperature: u8,
    pub dcdc4os_power_limit_power_electronics_temperature: u8,
    pub dcdc4os_power_limit_sli_battery_terminal_voltage: u8,
    pub dcdc4os_power_limit_sli_battery_terminal_current: u8,
    pub dcdc4os_power_limit_sli_battery_terminal_temperature: u8,
    pub dcdc4os_power_limit_undefined_reason: u8,
    pub dcdc4os_operating_status_counter: u8,
    pub dcdc4os_operating_status_crc: u8,

    // DCDC4S2 DC/DC Converter 4 Status 2
    pub dcdc4s2_low_side_power: f64,
    pub dcdc4s2_high_side_power: f64,
    pub dcdc4s2_high_side_ground_voltage: f64,

    // DCDC4SBS DC/DC Converter 4 SLI Battery Status
    pub dcdc4sbs_terminal_voltage: f64,
    pub dcdc4sbs_terminal_current: f64,
    pub dcdc4sbs_terminal_temperature: f64,

    // DCDC4T DC/DC Converter 4 Temperature
    pub dcdc4t_converter_temperature: f64,
    pub dcdc4t_electronic_filter_temperature: f64,
    pub dcdc4t_power_electronics_temperature: f64,
    pub dcdc4t_coolant_in_temperature: f64,
    pub dcdc4t_coolant_out_temperature: f64,

    // DCDC4V DC/DC Converter 4 Voltage
    pub dcdc4v_ignition_voltage: f64,
    pub dcdc4v_unswitched_sli_voltage: f64,

    // DCDC4VC DC/DC Converter 4 Voltage/Current
    pub dcdc4vc_low_side_voltage: f64,
    pub dcdc4vc_low_side_current: f64,
    pub dcdc4vc_high_side_voltage: f64,
    pub dcdc4vc_high_side_current: f64,

    // DCDC4SBL DC/DC Converter 4 SLI Battery Limits
    pub dcdc4sbl_voltage_max_limit: f64,
    pub dcdc4sbl_current_max_limit: f64,
    pub dcdc4sbl_temperature_max_limit: f64,

    // DCDC4LL DC/DC Converter 4 Low Side Limits
    pub dcdc4ll_low_side_voltage_min_limit: f64,
    pub dcdc4ll_low_side_voltage_max_limit: f64,
    pub dcdc4ll_low_side_current_max_limit: f64,
    pub dcdc4ll_low_side_current_min_limit: f64,

    // DCDC4HL DC/DC Converter 4 High Side Limits
    pub dcdc4hl_high_side_voltage_min_limit: f64,
    pub dcdc4hl_high_side_voltage_max_limit: f64,
    pub dcdc4hl_high_side_current_max_limit: f64,
    pub dcdc4hl_high_side_current_min_limit: f64,

    // DCDC4LD DC/DC Converter 4 Lifetime Data
    pub dcdc4ld_total_high_side_energy: f64,
    pub dcdc4ld_total_low_side_energy: f64,
    pub dcdc4ld_total_high_side_charge: f64,
    pub dcdc4ld_total_low_side_charge: f64,

    // DCDC4CFG1 DC/DC Converter 4 Configuration 1
    pub dcdc4cfg1_hs_voltage_min_limit: f64,
    pub dcdc4cfg1_hs_voltage_max_limit: f64,
    pub dcdc4cfg1_hs_current_max_limit: f64,
    pub dcdc4cfg1_ls_voltage_min_limit: f64,
    pub dcdc4cfg1_ls_voltage_max_limit: f64,
    pub dcdc4cfg1_ls_current_max_limit: f64,
    pub dcdc4cfg1_sli_voltage_max_limit: f64,
    pub dcdc4cfg1_sli_current_max_limit: f64,
    pub dcdc4cfg1_sli_temperature_max_limit: f64,
    pub dcdc4cfg1_ls_voltage_buck_default: f64,
    pub dcdc4cfg1_ls_current_min_limit: f64,
    pub dcdc4cfg1_hs_current_min_limit: f64,
}

impl Default for DcdcState {
    fn default() -> Self {
        Self {
            dcdc_operational_command: 1,
            dcdc_low_side_voltage_setpoint: 48.0,
            dcdc_high_side_voltage_setpoint: 800.0,
            dcdc_control_counter: 0,
            dcdc1os_hvil_status: 1,
            dcdc1os_loadshed_request: 0,
            dcdc1os_operational_status: 2,
            dcdc1os_operating_status_counter: 0,
            dcdc1os_operating_status_crc: 0,
            dcdc1os_power_limit_high_side_current: 0,
            dcdc1os_power_limit_low_side_current: 0,
            dcdc1os_power_limit_high_side_voltage_min: 0,
            dcdc1os_power_limit_high_side_voltage_max: 0,
            dcdc1os_power_limit_low_side_voltage_min: 0,
            dcdc1os_power_limit_low_side_voltage_max: 0,
            dcdc1os_power_limit_converter_temperature: 0,
            dcdc1os_power_limit_electronic_filter_temperature: 0,
            dcdc1os_power_limit_power_electronics_temperature: 0,
            dcdc1os_power_limit_sli_battery_terminal_voltage: 0,
            dcdc1os_power_limit_sli_battery_terminal_current: 0,
            dcdc1os_power_limit_sli_battery_terminal_temperature: 0,
            dcdc1os_power_limit_undefined_reason: 0,
            dcdc1sbs_terminal_current: 25.0,
            dcdc1sbs_terminal_voltage: 13.8,
            dcdc1sbs_terminal_temperature: 25.0,
            dcdc1s2_high_side_power: 200.0,
            dcdc1s2_low_side_power: -180.0,
            dcdc1s2_high_side_ground_voltage: 400.0,
            dcdc2sbs_terminal_voltage: 13.8,
            dcdc2sbs_terminal_current: -25.5,
            dcdc2sbs_terminal_temperature: 25.0,
            dcdc2s2_high_side_power: 200.0,
            dcdc2s2_low_side_power: -180.0,
            dcdc2s2_high_side_ground_voltage: 400.0,
            // === Batch 9: Extended Power Conversion defaults ===
            dcdc1hl_high_side_voltage_min_limit: 650.0,
            dcdc1hl_high_side_voltage_max_limit: 900.0,
            dcdc1hl_high_side_current_max_limit: 200.0,
            dcdc1hl_high_side_current_min_limit: -50.0,
            dcdc1ll_low_side_voltage_min_limit: 10.0,
            dcdc1ll_low_side_voltage_max_limit: 58.0,
            dcdc1ll_low_side_current_max_limit: 300.0,
            dcdc1ll_low_side_current_min_limit: -100.0,
            dcdc1t_converter_temperature: 45.0,
            dcdc1t_electronic_filter_temperature: 40.0,
            dcdc1t_power_electronics_temperature: 55.0,
            dcdc1t_coolant_in_temperature: 30.0,
            dcdc1t_coolant_out_temperature: 35.0,
            dcdc1v_ignition_voltage: 12.8,
            dcdc1v_unswitched_sli_voltage: 13.2,
            dcdc1vc_low_side_voltage: 48.0,
            dcdc1vc_low_side_current: 25.0,
            dcdc1vc_high_side_voltage: 800.0,
            dcdc1vc_high_side_current: 1.5,
            dcdc1ld_total_high_side_energy: 150000.0,
            dcdc1ld_total_low_side_energy: 145000.0,
            dcdc1ld_total_high_side_charge: 50000.0,
            dcdc1ld_total_low_side_charge: 48000.0,
            dcdc1sbl_voltage_max_limit: 16.0,
            dcdc1sbl_current_max_limit: 100.0,
            dcdc1sbl_temperature_max_limit: 60.0,
            dcdc1cfg1_hs_voltage_min_limit: 650.0,
            dcdc1cfg1_hs_voltage_max_limit: 900.0,
            dcdc1cfg1_hs_current_max_limit: 200.0,
            dcdc1cfg1_ls_voltage_min_limit: 10.0,
            dcdc1cfg1_ls_voltage_max_limit: 58.0,
            dcdc1cfg1_ls_current_max_limit: 300.0,
            dcdc1cfg1_sli_voltage_max_limit: 16.0,
            dcdc1cfg1_sli_current_max_limit: 100.0,
            dcdc1cfg1_sli_temperature_max_limit: 60.0,
            dcdc1cfg1_ls_voltage_buck_default: 48.0,
            dcdc1cfg1_ls_current_min_limit: -100.0,
            dcdc1cfg1_hs_current_min_limit: -50.0,
            dcdc2c_operational_command: 1,
            dcdc2c_control_counter: 0,
            dcdc2c_low_side_voltage_buck_setpoint: 48.0,
            dcdc2c_high_side_voltage_boost_setpoint: 800.0,
            dcdc2c_low_side_voltage_buck_default_setpoint: 48.0,
            dcdc2c_control_crc: 0,
            dcdc2os_operational_status: 2,
            dcdc2os_hvil_status: 1,
            dcdc2os_loadshed_request: 0,
            dcdc2os_power_limit_high_side_current: 0,
            dcdc2os_power_limit_low_side_current: 0,
            dcdc2os_power_limit_high_side_voltage_min: 0,
            dcdc2os_power_limit_high_side_voltage_max: 0,
            dcdc2os_power_limit_low_side_voltage_min: 0,
            dcdc2os_power_limit_low_side_voltage_max: 0,
            dcdc2os_power_limit_converter_temperature: 0,
            dcdc2os_power_limit_electronic_filter_temperature: 0,
            dcdc2os_power_limit_power_electronics_temperature: 0,
            dcdc2os_power_limit_sli_battery_terminal_voltage: 0,
            dcdc2os_power_limit_sli_battery_terminal_current: 0,
            dcdc2os_power_limit_sli_battery_terminal_temperature: 0,
            dcdc2os_power_limit_undefined_reason: 0,
            dcdc2os_operating_status_counter: 0,
            dcdc2os_operating_status_crc: 0,
            dcdc2hl_high_side_voltage_min_limit: 650.0,
            dcdc2hl_high_side_voltage_max_limit: 900.0,
            dcdc2hl_high_side_current_max_limit: 200.0,
            dcdc2hl_high_side_current_min_limit: -50.0,
            dcdc2ll_low_side_voltage_min_limit: 10.0,
            dcdc2ll_low_side_voltage_max_limit: 58.0,
            dcdc2ll_low_side_current_max_limit: 300.0,
            dcdc2ll_low_side_current_min_limit: -100.0,
            dcdc2t_converter_temperature: 45.0,
            dcdc2t_electronic_filter_temperature: 40.0,
            dcdc2t_power_electronics_temperature: 55.0,
            dcdc2t_coolant_in_temperature: 30.0,
            dcdc2t_coolant_out_temperature: 35.0,
            dcdc2v_ignition_voltage: 12.8,
            dcdc2v_unswitched_sli_voltage: 13.2,
            dcdc2vc_low_side_voltage: 48.0,
            dcdc2vc_low_side_current: 25.0,
            dcdc2vc_high_side_voltage: 800.0,
            dcdc2vc_high_side_current: 1.5,
            dcdc2ld_total_high_side_energy: 140000.0,
            dcdc2ld_total_low_side_energy: 135000.0,
            dcdc2ld_total_high_side_charge: 48000.0,
            dcdc2ld_total_low_side_charge: 46000.0,
            dcdc2sbl_voltage_max_limit: 16.0,
            dcdc2sbl_current_max_limit: 100.0,
            dcdc2sbl_temperature_max_limit: 60.0,
            dcdc2cfg1_hs_voltage_min_limit: 650.0,
            dcdc2cfg1_hs_voltage_max_limit: 900.0,
            dcdc2cfg1_hs_current_max_limit: 200.0,
            dcdc2cfg1_ls_voltage_min_limit: 10.0,
            dcdc2cfg1_ls_voltage_max_limit: 58.0,
            dcdc2cfg1_ls_current_max_limit: 300.0,
            dcdc2cfg1_sli_voltage_max_limit: 16.0,
            dcdc2cfg1_sli_current_max_limit: 100.0,
            dcdc2cfg1_sli_temperature_max_limit: 60.0,
            dcdc2cfg1_ls_voltage_buck_default: 48.0,
            dcdc2cfg1_ls_current_min_limit: -100.0,
            dcdc2cfg1_hs_current_min_limit: -50.0,
            dcdc3c_operational_command: 1,
            dcdc3c_control_counter: 0,
            dcdc3c_low_side_voltage_buck_setpoint: 48.0,
            dcdc3c_high_side_voltage_boost_setpoint: 800.0,
            dcdc3c_low_side_voltage_buck_default_setpoint: 48.0,
            dcdc3c_control_crc: 0,
            dcdc3os_operational_status: 2,
            dcdc3os_hvil_status: 1,
            dcdc3os_loadshed_request: 0,
            dcdc3os_power_limit_high_side_current: 0,
            dcdc3os_power_limit_low_side_current: 0,
            dcdc3os_power_limit_high_side_voltage_min: 0,
            dcdc3os_power_limit_high_side_voltage_max: 0,
            dcdc3os_power_limit_low_side_voltage_min: 0,
            dcdc3os_power_limit_low_side_voltage_max: 0,
            dcdc3os_power_limit_converter_temperature: 0,
            dcdc3os_power_limit_electronic_filter_temperature: 0,
            dcdc3os_power_limit_power_electronics_temperature: 0,
            dcdc3os_power_limit_sli_battery_terminal_voltage: 0,
            dcdc3os_power_limit_sli_battery_terminal_current: 0,
            dcdc3os_power_limit_sli_battery_terminal_temperature: 0,
            dcdc3os_power_limit_undefined_reason: 0,
            dcdc3os_operating_status_counter: 0,
            dcdc3os_operating_status_crc: 0,
            dcdc3s2_low_side_power: -170.0,
            dcdc3s2_high_side_power: 190.0,
            dcdc3s2_high_side_ground_voltage: 400.0,
            dcdc3sbs_terminal_voltage: 13.8,
            dcdc3sbs_terminal_current: 20.0,
            dcdc3sbs_terminal_temperature: 25.0,
            dcdc3t_converter_temperature: 42.0,
            dcdc3t_electronic_filter_temperature: 38.0,
            dcdc3t_power_electronics_temperature: 52.0,
            dcdc3t_coolant_in_temperature: 28.0,
            dcdc3t_coolant_out_temperature: 33.0,
            dcdc3v_ignition_voltage: 12.8,
            dcdc3v_unswitched_sli_voltage: 13.2,
            dcdc3vc_low_side_voltage: 48.0,
            dcdc3vc_low_side_current: 22.0,
            dcdc3vc_high_side_voltage: 800.0,
            dcdc3vc_high_side_current: 1.3,
            dcdc3sbl_voltage_max_limit: 16.0,
            dcdc3sbl_current_max_limit: 100.0,
            dcdc3sbl_temperature_max_limit: 60.0,
            dcdc3ll_low_side_voltage_min_limit: 10.0,
            dcdc3ll_low_side_voltage_max_limit: 58.0,
            dcdc3ll_low_side_current_max_limit: 300.0,
            dcdc3ll_low_side_current_min_limit: -100.0,
            dcdc3hl_high_side_voltage_min_limit: 650.0,
            dcdc3hl_high_side_voltage_max_limit: 900.0,
            dcdc3hl_high_side_current_max_limit: 200.0,
            dcdc3hl_high_side_current_min_limit: -50.0,
            dcdc3ld_total_high_side_energy: 130000.0,
            dcdc3ld_total_low_side_energy: 125000.0,
            dcdc3ld_total_high_side_charge: 45000.0,
            dcdc3ld_total_low_side_charge: 43000.0,
            dcdc3cfg1_hs_voltage_min_limit: 650.0,
            dcdc3cfg1_hs_voltage_max_limit: 900.0,
            dcdc3cfg1_hs_current_max_limit: 200.0,
            dcdc3cfg1_ls_voltage_min_limit: 10.0,
            dcdc3cfg1_ls_voltage_max_limit: 58.0,
            dcdc3cfg1_ls_current_max_limit: 300.0,
            dcdc3cfg1_sli_voltage_max_limit: 16.0,
            dcdc3cfg1_sli_current_max_limit: 100.0,
            dcdc3cfg1_sli_temperature_max_limit: 60.0,
            dcdc3cfg1_ls_voltage_buck_default: 48.0,
            dcdc3cfg1_ls_current_min_limit: -100.0,
            dcdc3cfg1_hs_current_min_limit: -50.0,
            dcdc4c_operational_command: 1,
            dcdc4c_control_counter: 0,
            dcdc4c_low_side_voltage_buck_setpoint: 48.0,
            dcdc4c_high_side_voltage_boost_setpoint: 800.0,
            dcdc4c_low_side_voltage_buck_default_setpoint: 48.0,
            dcdc4c_control_crc: 0,
            dcdc4os_operational_status: 2,
            dcdc4os_hvil_status: 1,
            dcdc4os_loadshed_request: 0,
            dcdc4os_power_limit_high_side_current: 0,
            dcdc4os_power_limit_low_side_current: 0,
            dcdc4os_power_limit_high_side_voltage_min: 0,
            dcdc4os_power_limit_high_side_voltage_max: 0,
            dcdc4os_power_limit_low_side_voltage_min: 0,
            dcdc4os_power_limit_low_side_voltage_max: 0,
            dcdc4os_power_limit_converter_temperature: 0,
            dcdc4os_power_limit_electronic_filter_temperature: 0,
            dcdc4os_power_limit_power_electronics_temperature: 0,
            dcdc4os_power_limit_sli_battery_terminal_voltage: 0,
            dcdc4os_power_limit_sli_battery_terminal_current: 0,
            dcdc4os_power_limit_sli_battery_terminal_temperature: 0,
            dcdc4os_power_limit_undefined_reason: 0,
            dcdc4os_operating_status_counter: 0,
            dcdc4os_operating_status_crc: 0,
            dcdc4s2_low_side_power: -160.0,
            dcdc4s2_high_side_power: 180.0,
            dcdc4s2_high_side_ground_voltage: 400.0,
            dcdc4sbs_terminal_voltage: 13.8,
            dcdc4sbs_terminal_current: 18.0,
            dcdc4sbs_terminal_temperature: 25.0,
            dcdc4t_converter_temperature: 40.0,
            dcdc4t_electronic_filter_temperature: 36.0,
            dcdc4t_power_electronics_temperature: 50.0,
            dcdc4t_coolant_in_temperature: 26.0,
            dcdc4t_coolant_out_temperature: 31.0,
            dcdc4v_ignition_voltage: 12.8,
            dcdc4v_unswitched_sli_voltage: 13.2,
            dcdc4vc_low_side_voltage: 48.0,
            dcdc4vc_low_side_current: 20.0,
            dcdc4vc_high_side_voltage: 800.0,
            dcdc4vc_high_side_current: 1.2,
            dcdc4sbl_voltage_max_limit: 16.0,
            dcdc4sbl_current_max_limit: 100.0,
            dcdc4sbl_temperature_max_limit: 60.0,
            dcdc4ll_low_side_voltage_min_limit: 10.0,
            dcdc4ll_low_side_voltage_max_limit: 58.0,
            dcdc4ll_low_side_current_max_limit: 300.0,
            dcdc4ll_low_side_current_min_limit: -100.0,
            dcdc4hl_high_side_voltage_min_limit: 650.0,
            dcdc4hl_high_side_voltage_max_limit: 900.0,
            dcdc4hl_high_side_current_max_limit: 200.0,
            dcdc4hl_high_side_current_min_limit: -50.0,
            dcdc4ld_total_high_side_energy: 120000.0,
            dcdc4ld_total_low_side_energy: 115000.0,
            dcdc4ld_total_high_side_charge: 42000.0,
            dcdc4ld_total_low_side_charge: 40000.0,
            dcdc4cfg1_hs_voltage_min_limit: 650.0,
            dcdc4cfg1_hs_voltage_max_limit: 900.0,
            dcdc4cfg1_hs_current_max_limit: 200.0,
            dcdc4cfg1_ls_voltage_min_limit: 10.0,
            dcdc4cfg1_ls_voltage_max_limit: 58.0,
            dcdc4cfg1_ls_current_max_limit: 300.0,
            dcdc4cfg1_sli_voltage_max_limit: 16.0,
            dcdc4cfg1_sli_current_max_limit: 100.0,
            dcdc4cfg1_sli_temperature_max_limit: 60.0,
            dcdc4cfg1_ls_voltage_buck_default: 48.0,
            dcdc4cfg1_ls_current_min_limit: -100.0,
            dcdc4cfg1_hs_current_min_limit: -50.0,
        }
    }
}
